name: Update streak stats

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch:   # Allows manual trigger
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Generate streak stats
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          options: "user=LeadingTheAbyss&theme=dark"
